version: "2.4"

services:
  ala-sensitive-data-service:
    container_name: "ala-sensitive-data-service"
    image: "charvolant/ala-sensitive-data-service:v20200214-3"
    ports:
      - "9190:9190"
      - "9189:9189"
