gbifApi:
  wsUrl: http://api.gbif.org
geocode:
  wsCacheSizeMb: 128
  api:
    wsUrl: https://api.gbif.org/v1/
extensionsAllowedForVerbatimSet:
  - http://rs.tdwg.org/dwc/terms/Occurrence
  - http://rs.tdwg.org/ac/terms/Multimedia
  - http://data.ggbn.org/schemas/ggbn/terms/Amplification
  - http://data.ggbn.org/schemas/ggbn/terms/Cloning
  - http://data.ggbn.org/schemas/ggbn/terms/GelImage
  - http://data.ggbn.org/schemas/ggbn/terms/Loan
  - http://data.ggbn.org/schemas/ggbn/terms/MaterialSample
  - http://data.ggbn.org/schemas/ggbn/terms/Permit
  - http://data.ggbn.org/schemas/ggbn/terms/Preparation
  - http://data.ggbn.org/schemas/ggbn/terms/Preservation
  - http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact
  - http://rs.tdwg.org/chrono/terms/ChronometricAge
  - http://purl.org/germplasm/germplasmTerm#GermplasmAccession
  - http://purl.org/germplasm/germplasmTerm#MeasurementScore
  - http://purl.org/germplasm/germplasmTerm#MeasurementTrait
  - http://purl.org/germplasm/germplasmTerm#MeasurementTrial
  - http://rs.tdwg.org/dwc/terms/Identification
  - http://rs.gbif.org/terms/1.0/Identifier
  - http://rs.gbif.org/terms/1.0/Image
  - http://rs.tdwg.org/dwc/terms/MeasurementOrFact
  - http://rs.gbif.org/terms/1.0/Multimedia
  - http://rs.gbif.org/terms/1.0/Reference
  - http://rs.tdwg.org/dwc/terms/ResourceRelationship
  - http://rs.gbif.org/terms/1.0/DNADerivedData
vocabularyConfig:
  vocabulariesPath: hdfs://ha-nn/pipelines/vocabularies
  vocabulariesNames:
    http://rs.gbif.org/terms/1.0/eventType: eventType
