# Deployment specific configuration for local machine using a locally installed HDFS.
# This file should be copied over `la-pipelines-local.yaml` when deployed
# so that it is used by the scripts.
#


index:
  inputPath: '{fsPath}/pipelines-data'
  solrCollection: biocache
  includeSampling: false
  includeImages: false
  includeSpeciesLists: true
  runner: SparkRunner
  zkHost: localhost:9983


speciesLists:
  runner: SparkRunner
  inputPath: '/data/pipelines-data'
  targetPath: '/data/pipelines-data'
  speciesAggregatesPath: '/data/pipelines-species'
  tempLocation: /tmp